
const cfg=window.WEDDING_CONFIG||{};
if(!cfg.supabaseUrl||cfg.supabaseUrl.includes("COLE_AQUI")||!cfg.supabaseAnonKey||cfg.supabaseAnonKey.includes("COLE_AQUI")){
 document.getElementById("setupError").classList.remove("hidden"); throw new Error("Supabase não configurado");
}
const db=window.supabase.createClient(cfg.supabaseUrl,cfg.supabaseAnonKey);
const state={settings:null,guests:[],tables:[],finance:[],gifts:[],tasks:[],edit:null};
const $=id=>document.getElementById(id);
const money=v=>Number(v||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const people=g=>Number(g.adults||0)+Number(g.children_0_8||0)+Number(g.children_9_12||0);
const weight=g=>Number(g.adults||0)*state.settings.adultWeight+Number(g.children_0_8||0)*state.settings.child08Weight+Number(g.children_9_12||0)*state.settings.child912Weight;
const seats=g=>(state.settings.adultSeat?Number(g.adults||0):0)+(state.settings.child08Seat?Number(g.children_0_8||0):0)+(state.settings.child912Seat?Number(g.children_9_12||0):0);
function notice(t){$("authNotice").textContent=t;$("authNotice").classList.remove("hidden")}
async function auth(){
 const {data:{session}}=await db.auth.getSession();
 if(session) showApp(); else $("authScreen").classList.remove("hidden");
}
$("loginBtn").onclick=async()=>{const {error}=await db.auth.signInWithPassword({email:$("email").value,password:$("password").value});error?notice(error.message):showApp()};
$("signupBtn").onclick=async()=>{const {error}=await db.auth.signUp({email:$("email").value,password:$("password").value});notice(error?error.message:"Conta criada. Confira seu e-mail se o Supabase solicitar confirmação.")};
$("logoutBtn").onclick=async()=>{await db.auth.signOut();location.reload()};
async function showApp(){$("authScreen").classList.add("hidden");$("app").classList.remove("hidden");await loadAll();subscribe()}
async function loadAll(){
 const [s,g,t,f,p,c]=await Promise.all([
  db.from("settings").select("*").eq("key","general").single(),
  db.from("guests").select("*").order("name"),
  db.from("wedding_tables").select("*").order("name"),
  db.from("finance").select("*").order("created_at",{ascending:false}),
  db.from("gifts").select("*").order("created_at",{ascending:false}),
  db.from("tasks").select("*").order("created_at",{ascending:false})
 ]);
 if(s.error) return alert("Erro ao carregar configurações: "+s.error.message);
 state.settings=s.data.value;state.guests=g.data||[];state.tables=t.data||[];state.finance=f.data||[];state.gifts=p.data||[];state.tasks=c.data||[];render();
}
function subscribe(){
 db.channel("planner").on("postgres_changes",{event:"*",schema:"public"},()=>loadAll()).subscribe();
}
const pages=[["dashboard","⌂","Dashboard"],["guests","👥","Convidados"],["tables","◉","Mesas"],["finance","R$","Financeiro"],["gifts","🎁","Presentes"],["tasks","✓","Checklist"],["settings","⚙","Configurações"]];
function render(){
 $("nav").innerHTML=pages.map((p,i)=>`<button class="${i===0?"active":""}" data-page="${p[0]}">${p[1]} ${p[2]}</button>`).join("");
 document.querySelectorAll("#nav button").forEach(b=>b.onclick=()=>openPage(b.dataset.page,b.textContent.replace(/^[^\s]+\s/,"")));
 renderBrand();renderDashboard();renderGuests();renderTables();renderFinance();renderGifts();renderTasks();renderSettings();
}
function openPage(id,title){document.querySelectorAll(".page").forEach(p=>p.classList.remove("active"));$(id).classList.add("active");document.querySelectorAll("#nav button").forEach(b=>b.classList.toggle("active",b.dataset.page===id));$("pageTitle").textContent=title;$("sidebar").classList.remove("open")}
$("menuBtn").onclick=()=>$("sidebar").classList.toggle("open");
function renderBrand(){const s=state.settings;$("brandTitle").textContent=s.appTitle;$("brandCouple").textContent=s.coupleNames;$("heroCouple").textContent=s.coupleNames;$("heroSubtitle").textContent=s.subtitle;$("brandDate").textContent=new Date(s.weddingDate+"T12:00").toLocaleDateString("pt-BR")+" • "+s.weddingTime;$("weddingLabel").textContent=new Date(s.weddingDate+"T"+s.weddingTime).toLocaleString("pt-BR",{dateStyle:"long",timeStyle:"short"})}
function tick(){if(!state.settings)return;let x=Math.max(0,new Date(state.settings.weddingDate+"T"+state.settings.weddingTime+":00-03:00")-Date.now());$("days").textContent=Math.floor(x/86400000);x%=86400000;$("hours").textContent=Math.floor(x/3600000);x%=3600000;$("minutes").textContent=Math.floor(x/60000);$("seconds").textContent=Math.floor((x%60000)/1000)}
setInterval(tick,1000);
function renderDashboard(){
 const gs=state.guests,conf=gs.filter(g=>g.rsvp_status==="Confirmado"),pend=gs.filter(g=>g.rsvp_status==="Pendente"),ref=gs.filter(g=>g.rsvp_status==="Recusado");
 const p=gs.reduce((a,g)=>a+people(g),0),w=gs.reduce((a,g)=>a+weight(g),0),st=gs.reduce((a,g)=>a+seats(g),0),nt=gs.filter(g=>!g.table_name).reduce((a,g)=>a+seats(g),0);
 $("kPeople").textContent=p;$("kConfirmed").textContent=conf.reduce((a,g)=>a+people(g),0)+" pessoas confirmadas";$("kWeight").textContent=w.toLocaleString("pt-BR");$("kLimit").textContent="de "+state.settings.guestLimit;$("kSeats").textContent=st;$("kNoTable").textContent=nt+" assentos sem mesa";
 const planned=state.finance.reduce((a,x)=>a+Number(x.planned),0),paid=state.finance.reduce((a,x)=>a+Number(x.paid),0);$("kBalance").textContent=money(planned-paid);$("kPaid").textContent=money(paid)+" pagos";
 const pct=gs.length?Math.round(conf.length/gs.length*100):0;$("confirmTitle").textContent=pct+"% das famílias confirmadas";$("confirmBar").style.width=pct+"%";$("confirmDetails").textContent=`${conf.length} confirmados, ${pend.length} pendentes e ${ref.length} recusados.`;
 $("categorySummary").textContent=`${gs.reduce((a,g)=>a+g.adults,0)} adultos, ${gs.reduce((a,g)=>a+g.children_0_8,0)} crianças de 0 a 8 e ${gs.reduce((a,g)=>a+g.children_9_12,0)} crianças de 9 a 12.`;
 const cap=state.tables.reduce((a,t)=>a+t.capacity,0);$("tableSummary").textContent=`${state.tables.length} mesas, ${cap} lugares e ${cap-st} disponíveis.`;
 const done=state.tasks.filter(t=>t.completed).length,tp=state.tasks.length?Math.round(done/state.tasks.length*100):0;$("taskBar").style.width=tp+"%";$("taskSummary").textContent=`${done} de ${state.tasks.length} tarefas concluídas.`;tick();
}
function badge(s){return `<span class="badge ${s==="Confirmado"?"ok":s==="Recusado"?"no":"wait"}">${s}</span>`}
function renderGuests(){const q=($("guestSearch").value||"").toLowerCase();$("guestRows").innerHTML=state.guests.filter(g=>(g.name+" "+g.side).toLowerCase().includes(q)).map(g=>`<tr><td>${g.name}</td><td>${g.side}</td><td>${g.adults}</td><td>${g.children_0_8}</td><td>${g.children_9_12}</td><td>${weight(g).toLocaleString("pt-BR")}</td><td>${seats(g)}</td><td>${g.invitation_status}</td><td>${badge(g.rsvp_status)}</td><td>${g.table_name||"Sem mesa"}</td><td><button class="secondary" onclick="guestModal('${g.id}')">Editar</button> <button class="danger" onclick="removeRow('guests','${g.id}')">Excluir</button></td></tr>`).join("")||`<tr><td colspan="11">Nenhum convidado.</td></tr>`}
$("guestSearch").oninput=renderGuests;$("addGuestBtn").onclick=()=>guestModal();
function modal(title,body){$("modalTitle").textContent=title;$("modalBody").innerHTML=body;$("modal").classList.remove("hidden")}
$("closeModal").onclick=()=>$("modal").classList.add("hidden");
window.guestModal=id=>{const g=state.guests.find(x=>x.id===id)||{name:"",side:"Flávio",adults:1,children_0_8:0,children_9_12:0,invitation_status:"Não enviado",rsvp_status:"Pendente",table_name:"",notes:""};state.edit=id;modal(id?"Editar convidado":"Novo convidado",`<div class="form"><label class="full">Nome ou família<input id="gName" value="${g.name}"></label><label>Lado<select id="gSide">${["Flávio","Nathália","Ambos"].map(x=>`<option ${x===g.side?"selected":""}>${x}</option>`)}</select></label><label>Adultos<input id="gAdults" type="number" min="0" value="${g.adults}"></label><label>0 a 8<input id="g08" type="number" min="0" value="${g.children_0_8}"></label><label>9 a 12<input id="g912" type="number" min="0" value="${g.children_9_12}"></label><label>Convite<select id="gInv">${["Não enviado","Enviado"].map(x=>`<option ${x===g.invitation_status?"selected":""}>${x}</option>`)}</select></label><label>Confirmação<select id="gRsvp">${["Pendente","Confirmado","Recusado"].map(x=>`<option ${x===g.rsvp_status?"selected":""}>${x}</option>`)}</select></label><label>Mesa<select id="gTable"><option value="">Sem mesa</option>${state.tables.map(t=>`<option ${t.name===g.table_name?"selected":""}>${t.name}</option>`)}</select></label><label class="full">Observações<textarea id="gNotes">${g.notes||""}</textarea></label></div><div class="actions"><button class="primary" onclick="saveGuest()">Salvar</button></div>`)}
window.saveGuest=async()=>{const obj={name:$("gName").value,side:$("gSide").value,adults:+$("gAdults").value,children_0_8:+$("g08").value,children_9_12:+$("g912").value,invitation_status:$("gInv").value,rsvp_status:$("gRsvp").value,table_name:$("gTable").value||null,notes:$("gNotes").value,updated_at:new Date().toISOString()};const r=state.edit?await db.from("guests").update(obj).eq("id",state.edit):await db.from("guests").insert(obj);if(r.error)alert(r.error.message);else $("modal").classList.add("hidden")}
function renderTables(){$("tableRows").innerHTML=state.tables.map(t=>{const o=state.guests.filter(g=>g.table_name===t.name).reduce((a,g)=>a+seats(g),0);return `<tr><td>${t.name}</td><td>${t.capacity}</td><td>${o}</td><td>${t.capacity-o}</td><td><button class="secondary" onclick="tableModal('${t.id}')">Editar</button> <button class="danger" onclick="removeRow('wedding_tables','${t.id}')">Excluir</button></td></tr>`}).join("")}
$("addTableBtn").onclick=()=>tableModal();window.tableModal=id=>{const t=state.tables.find(x=>x.id===id)||{name:"Mesa "+(state.tables.length+1),capacity:state.settings.defaultTableCapacity};state.edit=id;modal(id?"Editar mesa":"Nova mesa",`<div class="form"><label>Nome<input id="tName" value="${t.name}"></label><label>Capacidade<input id="tCap" type="number" value="${t.capacity}"></label></div><div class="actions"><button class="primary" onclick="saveTable()">Salvar</button></div>`)};window.saveTable=async()=>{const o={name:$("tName").value,capacity:+$("tCap").value};const r=state.edit?await db.from("wedding_tables").update(o).eq("id",state.edit):await db.from("wedding_tables").insert(o);if(r.error)alert(r.error.message);else $("modal").classList.add("hidden")}
function renderFinance(){$("financeRows").innerHTML=state.finance.map(x=>`<tr><td>${x.description}</td><td>${x.category}</td><td>${money(x.planned)}</td><td>${money(x.paid)}</td><td>${x.due_date||""}</td><td><button class="secondary" onclick="financeModal('${x.id}')">Editar</button> <button class="danger" onclick="removeRow('finance','${x.id}')">Excluir</button></td></tr>`).join("")}
$("addFinanceBtn").onclick=()=>financeModal();window.financeModal=id=>{const x=state.finance.find(y=>y.id===id)||{description:"",category:"",planned:0,paid:0,due_date:""};state.edit=id;modal(id?"Editar lançamento":"Novo lançamento",`<div class="form"><label class="full">Descrição<input id="fDesc" value="${x.description}"></label><label>Categoria<input id="fCat" value="${x.category}"></label><label>Previsto<input id="fPlan" type="number" step=".01" value="${x.planned}"></label><label>Pago<input id="fPaid" type="number" step=".01" value="${x.paid}"></label><label>Vencimento<input id="fDue" type="date" value="${x.due_date||""}"></label></div><div class="actions"><button class="primary" onclick="saveFinance()">Salvar</button></div>`)};window.saveFinance=async()=>{const o={description:$("fDesc").value,category:$("fCat").value,planned:+$("fPlan").value,paid:+$("fPaid").value,due_date:$("fDue").value||null};const r=state.edit?await db.from("finance").update(o).eq("id",state.edit):await db.from("finance").insert(o);if(r.error)alert(r.error.message);else $("modal").classList.add("hidden")}
function renderGifts(){$("giftRows").innerHTML=state.gifts.map(x=>`<tr><td>${x.item}</td><td>${x.given_by}</td><td>${x.received?"Sim":"Não"}</td><td>${x.thanked?"Enviado":"Pendente"}</td><td><button class="secondary" onclick="giftModal('${x.id}')">Editar</button> <button class="danger" onclick="removeRow('gifts','${x.id}')">Excluir</button></td></tr>`).join("")}
$("addGiftBtn").onclick=()=>giftModal();window.giftModal=id=>{const x=state.gifts.find(y=>y.id===id)||{item:"",given_by:"",received:false,thanked:false};state.edit=id;modal(id?"Editar presente":"Novo presente",`<div class="form"><label class="full">Presente<input id="pItem" value="${x.item}"></label><label class="full">Quem deu<input id="pFrom" value="${x.given_by}"></label><label>Recebido<select id="pRec"><option value="false">Não</option><option value="true" ${x.received?"selected":""}>Sim</option></select></label><label>Agradecimento<select id="pThanks"><option value="false">Pendente</option><option value="true" ${x.thanked?"selected":""}>Enviado</option></select></label></div><div class="actions"><button class="primary" onclick="saveGift()">Salvar</button></div>`)};window.saveGift=async()=>{const o={item:$("pItem").value,given_by:$("pFrom").value,received:$("pRec").value==="true",thanked:$("pThanks").value==="true"};const r=state.edit?await db.from("gifts").update(o).eq("id",state.edit):await db.from("gifts").insert(o);if(r.error)alert(r.error.message);else $("modal").classList.add("hidden")}
function renderTasks(){$("taskList").innerHTML=state.tasks.map(x=>`<div style="display:flex;align-items:center;gap:10px;padding:11px;border-bottom:1px solid #eee"><input type="checkbox" ${x.completed?"checked":""} onchange="toggleTask('${x.id}',this.checked)"><span style="flex:1;${x.completed?"text-decoration:line-through":""}">${x.title}</span><button class="danger" onclick="removeRow('tasks','${x.id}')">Excluir</button></div>`).join("")||"<p>Nenhuma tarefa.</p>"}
$("addTaskBtn").onclick=()=>{state.edit=null;modal("Nova tarefa",`<div class="form"><label class="full">Tarefa<input id="cTitle"></label><label>Data<input id="cDue" type="date"></label></div><div class="actions"><button class="primary" onclick="saveTask()">Salvar</button></div>`)};window.saveTask=async()=>{const r=await db.from("tasks").insert({title:$("cTitle").value,due_date:$("cDue").value||null});if(r.error)alert(r.error.message);else $("modal").classList.add("hidden")};window.toggleTask=async(id,v)=>db.from("tasks").update({completed:v}).eq("id",id)
window.removeRow=async(table,id)=>{if(confirm("Excluir este item?")){const {error}=await db.from(table).delete().eq("id",id);if(error)alert(error.message)}}
function renderSettings(){const s=state.settings;$("sAppTitle").value=s.appTitle;$("sCoupleNames").value=s.coupleNames;$("sDate").value=s.weddingDate;$("sTime").value=s.weddingTime;$("sSubtitle").value=s.subtitle;$("sGuestLimit").value=s.guestLimit;$("sCapacity").value=s.defaultTableCapacity;$("sAdultWeight").value=s.adultWeight;$("sChild08Weight").value=s.child08Weight;$("sChild912Weight").value=s.child912Weight;$("sAdultSeat").value=String(s.adultSeat);$("sChild08Seat").value=String(s.child08Seat);$("sChild912Seat").value=String(s.child912Seat)}
$("saveSettingsBtn").onclick=async()=>{const value={appTitle:$("sAppTitle").value,coupleNames:$("sCoupleNames").value,weddingDate:$("sDate").value,weddingTime:$("sTime").value,subtitle:$("sSubtitle").value,guestLimit:+$("sGuestLimit").value,defaultTableCapacity:+$("sCapacity").value,adultWeight:+$("sAdultWeight").value,child08Weight:+$("sChild08Weight").value,child912Weight:+$("sChild912Weight").value,adultSeat:$("sAdultSeat").value==="true",child08Seat:$("sChild08Seat").value==="true",child912Seat:$("sChild912Seat").value==="true"};const {error}=await db.from("settings").update({value,updated_at:new Date().toISOString()}).eq("key","general");alert(error?error.message:"Configurações salvas.")};
auth();
